Repository Mattheop/IUT-ESporter, pull requests merged in 2023-02, with the labels that each got.

#3 feat(tournoi-add-form): fix issue #2
  src/main/resources/templates/organisateur/tournois/create.html
Labels: invalid

#4 feat(forms): fix issue #1 Placeholders forms
  pom.xml
  src/main/resources/templates/ecurie/joueurs/ajout.html
  src/main/resources/templates/ecurie/joueurs/edit.html
  src/main/resources/templates/organisateur/tournois/create.html
Labels: enhancement

#8 feat(tournoi-add-form): fix issue #6
  src/main/resources/templates/organisateur/tournois/create.html
Labels: invalid

#10 fix(sidebar-header): fix issue #9
  src/main/java/com/example/sae/models/db/AppUser.java
  src/main/resources/templates/fragments/dashboard/sidebar.html
Labels: bug

#19 Validation & retour utilisateur sur les formulaires
  pom.xml
  src/main/java/com/example/sae/SaeApplication.java
  src/main/java/com/example/sae/controller/ecurie/EcurieGestionEquipeController.java
  src/main/java/com/example/sae/controller/ecurie/EcurieGestionJoueurController.java
  src/main/java/com/example/sae/controller/organisateur/OrganisateurGestionTournoisController.java
  src/main/java/com/example/sae/models/db/Competition.java
  src/main/java/com/example/sae/models/db/Equipe.java
  src/main/java/com/example/sae/models/db/Joueur.java
  src/main/java/com/example/sae/models/db/Tournois.java
  src/main/java/com/example/sae/validation/DateInline/CompetitionDateInlineValidator.java
  src/main/java/com/example/sae/validation/DateInline/ValidCompetitionDateIsInline.java
  src/main/resources/static/css/form.css
  src/main/resources/templates/ecurie/equipes/ajout.html
  src/main/resources/templates/ecurie/joueurs/ajout.html
  src/main/resources/templates/organisateur/tournois/addCompetition.html
  src/main/resources/templates/organisateur/tournois/create.html
  src/main/resources/validations-feedback.properties
Labels: bug, critical

#25 fix(competition): fix multiple competitions
  src/main/java/com/example/sae/controller/organisateur/OrganisateurGestionTournoisController.java
  src/main/java/com/example/sae/repository/JeuRepository.java
  src/main/resources/templates/organisateur/tournois/addCompetition.html
Labels: bug

#28 fix(competition): fix multiple inscription #27
  src/main/java/com/example/sae/controller/ecurie/CompetitionController.java
  src/main/java/com/example/sae/repository/EquipeRepository.java
Labels: bug

#30 Génération automatique des rencontres
  sql/trigger/AI_INSCRIPTION_GENERATION_POULES.sql
  src/main/java/com/example/sae/controller/arbitre/ArbitreScoreRest.java
  src/main/java/com/example/sae/controller/arbitre/RESTBody/ArbitreScoreRESTBody.java
  src/main/java/com/example/sae/models/db/Rencontre.java
  src/main/java/com/example/sae/repository/RencontreRepository.java
  src/main/resources/static/js/app.js
  src/main/resources/templates/arbitre/competitionDetails.html
Labels: bug, critical

#32 Changement arbitrage score
  src/main/java/com/example/sae/controller/arbitre/ArbitreCompetitionDetails.java
  src/main/java/com/example/sae/models/db/Competition.java
  src/main/java/com/example/sae/models/db/Rencontre.java
  src/main/resources/static/css/app.css
  src/main/resources/static/css/dashboard.css
  src/main/resources/templates/arbitre/competitionDetails.html
Labels: bug
